### ISSUE TITLE
Android Build issue with latest SDK 2.0.3 - Multiple dex files define Landroid/support/annotation/AnimRes

### ISSUE THREAD

**Issue by tkuben** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#68] opened 2016-03-11 18:10 UTC
Hi 

I am using the latest master I believe its 2.0.3 and when I build on the android, I am getting the following error: 

```
UNEXPECTED TOP-LEVEL EXCEPTION:

com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;


	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)


	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)


	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)


	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)


	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)


	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)


	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)


	at com.android.dx.command.dexer.Main.run(Main.java:277)


	at com.android.dx.command.dexer.Main.main(Main.java:245)


	at com.android.dx.command.Main.main(Main.java:106)




 
FAILED


```

When I remove the branch plugin and try, I am able to build successfully. 

Any Thoughts? 
Cheers

TJ

**Comment by aaustin** [comment] 2016-03-12 00:17
Hey @tkuben. That's super weird. Here are a few things we've found to trigger the DexException in the past:
- Conflicting classes in external libraries
- Reaching limits on total number of methods used in Android

A quick fix is to add `multiDex enabled` to the build.gradle. However, my bet is that you just need to delete the old Branch android import folder and reimport. I bet it's not cleaning out the old version or something.

**Comment by harshabonthu** [comment] 2016-03-12 19:44
Yes this is related to not removing the branch.jar from `libs` folder. 2.0.2 plugin was adding a branch.jar and 2.0.3 plugin is importing the framework by adding to build.gradle as dependency from maven repo.

**Comment by tkuben** [comment] 2016-03-12 19:57
Hi @harshabonthu , @aaustin 

I unfortunately do not have a branch.jar in my libs: 

```
ls -altr platforms/android/libs/
total 1216
-rw-r--r--   1 tkuben  staff  622059 13 Jan 20:45 com.google.zxing.client.android.captureactivity.jar
drwxr-xr-x   3 tkuben  staff     102 11 Mar 11:39 .
drwxr-xr-x  24 tkuben  staff     816 12 Mar 14:49 ..
ThusiMacAir:mobile tkuben$ find . -iname "branch.jar"
ThusiMacAir:mobile tkuben$ 

```

When I add multiDexEnabled true to my build.gradle, I get the following error:
```

:compileDebugJava
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
Note: /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/src/io/branch/BranchSDK.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.



:packageAllDebugClassesForMultiDex
 
FAILED



FAILURE: 
Build failed with an exception.


* What went wrong:

Execution failed for task ':packageAllDebugClassesForMultiDex'.

> java.util.zip.ZipException: duplicate entry: android/support/annotation/AttrRes.class
```


When I remove io.branch.sdk plugin and try, I am able to build without any issues... The following are my dependencies in my build.gradle: 

```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    debugCompile project(path: "phonegap-facebook-plugin:FacebookLib", configuration: "debug")
    releaseCompile project(path: "phonegap-facebook-plugin:FacebookLib", configuration: "release")
    compile "com.google.android.gms:play-services-plus:+"
    compile "com.google.android.gms:play-services-identity:+"
    compile "io.branch.sdk.android:library:1.+"
    // SUB-PROJECT DEPENDENCIES END
}
```

Any thoughts? 

Cheers, 
TJ

**Comment by harshabonthu** [comment] 2016-03-12 20:10
Sorry, I think you searched for branch.jar try the exact file name i.e "Branch-1.10.3.jar". 

Can you reset the project i.e removing android platform and adding again ? 

```

-  cordova plugin rm io.branch.sdk
-  cordova platform rm android
-  cordova platform add android
-  cordova build
-  cordova plugin add branch-cordova-sdk --save
-  cordova build

```

**Comment by aaustin** [comment] 2016-03-12 20:11
Thanks for your help @harshabonthu !!

**Comment by renesansz** [comment] 2016-03-14 03:02
Hello @tkuben,
Are you still having this problem? let us know if @harshabonthu 's solution still doesn't work.
Thanks

**Comment by tkuben** [comment] 2016-03-14 04:46
Hi @harshabonthu & @aaustin 

Unfortunately that did not resolve the issue. Please see the logs below:

```
ThusiMacAir:mobile tkuben$ cordova plugin remove io.branch.sdk
Error: Plugin "io.branch.sdk" is not present in the project. See `cordova plugin list`.


ThusiMacAir:mobile tkuben$ cordova platform remove android
ThusiMacAir:mobile tkuben$ cordova platform add android
Adding android project...

Running command: /Users/tkuben/.cordova/lib/npm_cache/cordova-android/4.1.1/package/bin/create /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android com.phonegap.riipe Riipe --cli

Creating Cordova project for the Android platform:

        Path: platforms/android

        Package: com.phonegap.riipe

        Name: Riipe

        Activity: MainActivity
        Android target: android-22
Copying template files...

Android project created with cordova-android@4.1.1

Installing "cordova-plugin-camera" for android

Installing "cordova-plugin-console" for android

Installing "cordova-plugin-dialogs" for android

Installing "cordova-plugin-googleplus" for android

Installing "cordova-plugin-splashscreen" for android

Installing "cordova-plugin-whitelist" for android


               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          

Installing "cordova-plugin-x-socialsharing" for android

Installing "cordova-universal-links-plugin" for android

Installing "phonegap-facebook-plugin" for android

Installing "phonegap-plugin-barcodescanner" for android

ThusiMacAir:mobile tkuben$ cat build-extras.gradle 
configurations {
all*.exclude group: 'com.android.support', module: 'support-v4'
}ThusiMacAir:mobile tkuben$ cp build-extras.gradle platforms/android/
ThusiMacAir:mobile tkuben$ cordova build
[phonegap] executing 'cordova build'...
[phonegap] completed 'cordova build'
ThusiMacAir:mobile tkuben$ cordova plugin add https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git --variable BRANCH_KEY=key_live_ofnHQuHR629tFEiZbBQOzklkwEfPO8Xw --variable BRANCH_TEST_KEY=key_test_pdeJSvVU09YwEFlZiB6dcihiuqnHJ26V --variable URI_SCHEME=riipe
Fetching plugin "https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git" via git clone

Repository "https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git" checked out to git ref "master".

Installing "io.branch.sdk" for android

Checking dependencies:

    Node module mkpath is found

    Module mkpath is installed

    Node module node-version-compare is found
    Module node-version-compare is installed

    Node module plist is found

    Module plist is installed

    Node module rimraf is found

    Module rimraf is installed

    Node module xml2js is found

    Module xml2js is installed

Installing "io.branch.sdk" for ios

ThusiMacAir:mobile tkuben$ cordova build
[phonegap] executing 'cordova build'...

IOS project Code Sign Entitlements now set to: Riipe/Resources/Riipe.entitlements

Entitlements file is not in references section, adding it

<branch-config> tag is not set in the config.xml. Universal Links plugin is not going to work.

Running command: /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/cordova/build 

ANDROID_HOME=/Users/tkuben/Library/Android/sdk

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home

Running: /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/gradlew cdvBuildDebug -b /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/build.gradle -Dorg.gradle.daemon=true

:preBuild


:compileDebugNdk
 
UP-TO-DATE

:preDebugBuild


:checkDebugManifest


:CordovaLib:compileLint


:CordovaLib:copyDebugLint
 UP-TO-DATE


:CordovaLib:mergeDebugProguardFiles
 UP-TO-DATE

:CordovaLib:preBuild


:CordovaLib:preDebugBuild


:CordovaLib:checkDebugManifest


:CordovaLib:prepareDebugDependencies


:CordovaLib:compileDebugAidl
 
UP-TO-DATE

:CordovaLib:compileDebugRenderscript
 UP-TO-DATE

:CordovaLib:generateDebugBuildConfig
 
UP-TO-DATE

:CordovaLib:generateDebugAssets
 
UP-TO-DATE

:CordovaLib:mergeDebugAssets
 
UP-TO-DATE

:CordovaLib:generateDebugResValues
 UP-TO-DATE


:CordovaLib:generateDebugResources
 
UP-TO-DATE

:CordovaLib:packageDebugResources
 
UP-TO-DATE

:CordovaLib:processDebugManifest
 
UP-TO-DATE

:CordovaLib:processDebugResources
 
UP-TO-DATE

:CordovaLib:generateDebugSources
 
UP-TO-DATE

:CordovaLib:compileDebugJava
 
UP-TO-DATE

:CordovaLib:processDebugJavaRes
 
UP-TO-DATE

:CordovaLib:packageDebugJar
 
UP-TO-DATE

:CordovaLib:compileDebugNdk
 
UP-TO-DATE

:CordovaLib:packageDebugJniLibs
 
UP-TO-DATE

:CordovaLib:packageDebugLocalJar
 
UP-TO-DATE


:CordovaLib:packageDebugRenderscript
 
UP-TO-DATE


:CordovaLib:bundleDebug
 
UP-TO-DATE


:phonegap-facebook-plugin:FacebookLib:compileLint


:phonegap-facebook-plugin:FacebookLib:copyDebugLint
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:mergeDebugProguardFiles
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:preBuild


:phonegap-facebook-plugin:FacebookLib:preDebugBuild


:phonegap-facebook-plugin:FacebookLib:checkDebugManifest


:phonegap-facebook-plugin:FacebookLib:preDebugTestBuild


:phonegap-facebook-plugin:FacebookLib:prepareAndroidCordovaLibUnspecifiedDebugLibrary
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:prepareDebugDependencies


:phonegap-facebook-plugin:FacebookLib:compileDebugAidl
 
UP-TO-DATE


:phonegap-facebook-plugin:FacebookLib:compileDebugRenderscript
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateDebugBuildConfig
 UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateDebugAssets
 UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:mergeDebugAssets
 
UP-TO-DATE
:phonegap-facebook-plugin:FacebookLib:generateDebugResValues
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateDebugResources
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:mergeDebugResources
 
UP-TO-DATE


:phonegap-facebook-plugin:FacebookLib:processDebugManifest
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:processDebugResources
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateDebugSources
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:compileDebugJava
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:processDebugJavaRes
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageDebugJar
 
UP-TO-DATE


:phonegap-facebook-plugin:FacebookLib:compileDebugNdk
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageDebugJniLibs
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageDebugLocalJar
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageDebugRenderscript
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageDebugResources
 UP-TO-DATE


:phonegap-facebook-plugin:FacebookLib:bundleDebug
 
UP-TO-DATE

:prepareAndroidCordovaLibUnspecifiedDebugLibrary
 
UP-TO-DATE

:prepareAndroidPhonegapFacebookPluginFacebookLibUnspecifiedDebugLibrary
 
UP-TO-DATE


:preReleaseBuild


:CordovaLib:copyReleaseLint
 
UP-TO-DATE

:CordovaLib:mergeReleaseProguardFiles
 
UP-TO-DATE

:CordovaLib:preReleaseBuild


:CordovaLib:checkReleaseManifest


:CordovaLib:prepareReleaseDependencies


:CordovaLib:compileReleaseAidl
 
UP-TO-DATE

:CordovaLib:compileReleaseRenderscript
 
UP-TO-DATE

:CordovaLib:generateReleaseBuildConfig
 UP-TO-DATE


:CordovaLib:generateReleaseAssets
 
UP-TO-DATE

:CordovaLib:mergeReleaseAssets
 
UP-TO-DATE

:CordovaLib:generateReleaseResValues
 
UP-TO-DATE


:CordovaLib:generateReleaseResources
 
UP-TO-DATE

:CordovaLib:packageReleaseResources
 
UP-TO-DATE

:CordovaLib:processReleaseManifest
 
UP-TO-DATE

:CordovaLib:processReleaseResources
 
UP-TO-DATE


:CordovaLib:generateReleaseSources
 UP-TO-DATE


:CordovaLib:compileReleaseJava
 
UP-TO-DATE


:CordovaLib:processReleaseJavaRes
 
UP-TO-DATE

:CordovaLib:packageReleaseJar
 
UP-TO-DATE

:CordovaLib:compileReleaseNdk
 
UP-TO-DATE

:CordovaLib:packageReleaseJniLibs
 
UP-TO-DATE

:CordovaLib:packageReleaseLocalJar
 
UP-TO-DATE

:CordovaLib:packageReleaseRenderscript
 
UP-TO-DATE

:CordovaLib:bundleRelease
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:copyReleaseLint
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:mergeReleaseProguardFiles
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:preReleaseBuild


:phonegap-facebook-plugin:FacebookLib:checkReleaseManifest


:phonegap-facebook-plugin:FacebookLib:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:prepareReleaseDependencies


:phonegap-facebook-plugin:FacebookLib:compileReleaseAidl
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:compileReleaseRenderscript
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateReleaseBuildConfig
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateReleaseAssets
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:mergeReleaseAssets
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateReleaseResValues
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateReleaseResources
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:mergeReleaseResources
 UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:processReleaseManifest
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:processReleaseResources
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:generateReleaseSources
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:compileReleaseJava
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:processReleaseJavaRes
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageReleaseJar
 
UP-TO-DATE


:phonegap-facebook-plugin:FacebookLib:compileReleaseNdk
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageReleaseJniLibs
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageReleaseLocalJar
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageReleaseRenderscript
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:packageReleaseResources
 
UP-TO-DATE

:phonegap-facebook-plugin:FacebookLib:bundleRelease
 
UP-TO-DATE

:prepareComGoogleAndroidGmsPlayServicesBase840Library
 
UP-TO-DATE

:prepareComGoogleAndroidGmsPlayServicesBasement840Library
 
UP-TO-DATE

:prepareComGoogleAndroidGmsPlayServicesIdentity840Library
 UP-TO-DATE


:prepareComGoogleAndroidGmsPlayServicesPlus840Library
 
UP-TO-DATE


:prepareIoBranchSdkAndroidLibrary1108Library


:prepareDebugDependencies


:compileDebugAidl
 
UP-TO-DATE

:compileDebugRenderscript


:generateDebugBuildConfig
 UP-TO-DATE


:generateDebugAssets
 
UP-TO-DATE

:mergeDebugAssets


:generateDebugResValues
 
UP-TO-DATE

:generateDebugResources


:mergeDebugResources
/Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/res/drawable-xxhdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited


/Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/res/drawable-mdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited


/Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/res/drawable-hdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited



:processDebugManifest


:processDebugResources
warning: string 'menu_settings' has no default translation.




:generateDebugSources


:compileDebugJava
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/src/io/branch/BranchSDK.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.



:preDexDebug


:dexDebug


UNEXPECTED TOP-LEVEL EXCEPTION:

com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;


        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)


        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)


        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)


        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)


        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)

        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)


        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)


        at com.android.dx.command.dexer.Main.run(Main.java:277)

        at com.android.dx.command.dexer.Main.main(Main.java:245)


        at com.android.dx.command.Main.main(Main.java:106)




 
FAILED



FAILURE: Build failed with an exception.



* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:

        /Users/tkuben/Library/Android/sdk/build-tools/23.0.2/dx --dex --no-optimize --output /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/build/intermediates/dex/debug --input-list=/Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
        2
  Output:
        

        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)

                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)

                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)

                at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)

                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)

                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)

                at com.android.dx.command.dexer.Main.run(Main.java:277)

                at com.android.dx.command.dexer.Main.main(Main.java:245)

                at com.android.dx.command.Main.main(Main.java:106)

        





* Try:

Run with 
--stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.



BUILD FAILED




Total time: 51.42 secs


/Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^

Error code 1 for command: /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/gradlew with args: cdvBuildDebug,-b,/Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/build.gradle,-Dorg.gradle.daemon=true

ERROR building one of the platforms: Error: /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project

Error: /Users/tkuben/Documents/webroot/riipe/mobile/platforms/android/cordova/build: Command failed with exit code 1
```


The following are the plugins I have installed: 
```

cordova-plugin-camera 2.1.0 "Camera"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-googleplus 4.0.8 "Google+"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.0.9 "SocialSharing"
cordova-universal-links-plugin 1.1.0 "Universal Links Plugin"
io.branch.sdk 2.0.3 "branch-cordova-sdk"
phonegap-facebook-plugin 0.12.0 "Facebook Connect"
phonegap-plugin-barcodescanner 4.1.0 "BarcodeScanner"
```

Cheers, 
TJ

**Comment by tkuben** [comment] 2016-03-14 04:57
Hi Renemari,

Unfortunately it is still an issue. Please see the comment on github:

https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/68

Your help in solving this matter would be much appreciated. I believe it
has to do with conflicting libraries between the facebook plugin and
branch. In particular it probably has something to do with:
com.android.support:support-annotations:22.2.0 &
 FacebookLib/libs/android-support-v4.jar

Your help would be much appareciated...

Cheers,
TJ

On Sun, Mar 13, 2016 at 11:02 PM, Renemari Padillo <notifications@github.com
> wrote:

> Hello @tkuben <https://github.com/tkuben>,
> Are you still having this problem? let us know if @harshabonthu
> <https://github.com/harshabonthu> 's solution still doesn't work.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/68#issuecomment-196117849>
> .
>



-- 
Thusjanthan Kubendranathan M.Sc.
CTO & Co-Founder
http://www.realtyforsale.ca
p: 647-869-7284

**Comment by renesansz** [comment] 2016-03-14 06:00
Hello @tkuben ,
I see, I'll look into the logs and I'll try to replicate your issue.
I'll give you an update once I've found the cause of the error.

Thanks

**Comment by renesansz** [comment] 2016-03-14 08:24
By the way,
@tkuben could you also list the plugins including your plugin parameters upon installing them?
Or anything that would help me replicate your issue, as I find it difficult the your installed plugins.

Thanks

**Comment by renesansz** [comment] 2016-03-14 10:07
Hey @tkuben ,

Would like to inform you that the problem you are having is not from our plugin but from the `phonegap-facebook-plugin` itself. So dig through on this [article](https://github.com/Wizcorp/phonegap-facebook-plugin/issues/992).

And I was able to solve the library conflict for the `phonegap-facebook-plugin`, by doing the ff:

* Replace the `android-support-v4.jar` that comes with the plugin with my Android SDK `android-support-v4.jar` file.

So in my case, my `android-support-v4.jar` SDK file resides on this directory
```
/Users/renesansz/Library/Android/sdk/extras/android/m2repository/com/android/support/support-v4/13.0.0
```

So I copied the `support-v4-13.0.0.jar` file and replaced `android-support-v4.jar` in
```
<your-app-directory>/platform/android/phonegap-facebook-plugin/testbed-FacebookLib/libs/android-support-v4.jar
```

Then I recompiled the app and now it successfully builds the app!

Let me know if it still doesn't worked for you.

**Comment by harshabonthu** [comment] 2016-03-14 14:12
@tkuben Also you don't need to add `cordova-universal-links-plugin` starting from 2.0.2, it would result in conflicts and may result in not getting the params from branch links.

**Comment by tkuben** [comment] 2016-03-15 13:51
Hi @harshabonthu 

Thank you. Replacing the android-support-v4.jar with the older version does allow me to compile. However, I think there is still some issues with the FB plugin which I will take a look at. 

With Branch, on ios with the latest 2.0.5 version I am able to create the links. However, now I am back to an older problem where the links are not opening up the app on the phone but rather it opens the download link. I am able to open safari and type in: <SCHEME NAME>:// and it opens the app. 

Any thoughts? Am I doing something incorrect here? 

If I do open the app by myself manually, the custom meta data does get loaded into the app... strange.. 

Cheers, 
TJ

**Comment by renesansz** [comment] 2016-03-15 15:49
@tkuben , can you show us your `config.xml`?

Thanks

**Comment by tkuben** [comment] 2016-03-15 18:43
Hi @renesansz 

I am currently removing the Google/FB and Branch plugins and readding them one at a time to track down which plugin(s) are having dependency issues. 

Currently 1 issue so far is between FB & Branch on iOS. FB alone works fine, but after branch FB login on ios does not work. Please see this issue: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/72

Cheers, 
TJ

**Comment by renesansz** [comment] 2016-03-16 04:04
Hello @tkuben ,
I see, I'll look into it.
I'll close this issue now since the problem has been already resolved.

**Closed by renesansz** 2016-03-16 04:04 UTC

**Comment by yonihei** [comment] 2016-04-20 17:56
i had this problem with Wizcorp/phonegap-facebook-plugin
I moved to https://github.com/jeduan/cordova-plugin-facebook4
didnt have to change even one line of code
