### ISSUE TITLE
minor inconsistencies between ios & android

### ISSUE THREAD

**Issue by yonihei** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#136] opened 2016-05-03 16:33 UTC
1) function DeepLinkHandler(link): in ios, the link's data is: link.data.params, however in android it is: link.data   - Edit - this thing has already been fixed in some other issue.
2) when creating a new universal link using createBranchUniversalObject and generateShortUrl and using $ios_url and $android_url, they need to be in different places to work:

on IOS it needs to be inside contentMetadata inside createBranchUniversalObject's input.
on Android it needs to be inside generateShortUrl's second object parameter.

i hope that i saved some time to someone :P

**Comment by renesansz** [comment] 2016-05-03 17:00
Hey @yonihei , thanks for reporting.
To answer your question:
1. Yes, this was fixed in PR #127 
2. To clarify your confusion, `$android_url` can still be passed in `contentMetadata` in `createUniversalObject` method for Android. See this [line](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/blob/master/src/android/io/branch/BranchSDK.java#L380) for reference. If however, you still think that this is not working as intended, can you provide a sample data comparison?

Cheers,
Rene

**Comment by yonihei** [comment] 2016-05-03 20:45
What i mean is that in the documentation of "generateShortUr", controlParameters, it is written we can add $ios_url and such. However, it does NOT work adding these for IOS (only for android).

**Comment by renesansz** [comment] 2016-05-03 21:57
Can you provide a log of the result of the method? Also, include your source code.
I've tried to replicate the issue and the method works as intended.
Here's the data from the log.
```
May  4 05:53:52 Renesansz-MBPro Branch.IO Testbed[4245]: [BNCServerInterface.m:183] body = {
	    alias = "";
	    "branch_key" = "key_live_fnmRM1FXtu11t6e4LU8WsldpvDcA0bzv";
	    channel = test;
	    data =     {
	        "$android_url" = test;
	        "$blackberry_url" = blackberry;
	        "$canonical_identifier" = testbed;
	        "$desktop_url" = "www.desktop.com";
	        "$exp_date" = 0;
	        "$fallback_url" = "www.another.com";
	        "$fire_url" = fire;
	        "$ios_url" = ios;
	        "$ipad_url" = ipad;
	        "$og_description" = "Testbed Application";
	        "$og_image_url" = "https://imgflip.com/s/meme/Derp.jpg";
	        "$og_title" = testbed;
	        "$publicly_indexable" = 1;
	        "$windows_phone_url" = "win-phone";
	    };
	    "device_fingerprint_id" = 245066530092558235;
	    duration = 10000;
	    feature = test;
	    "identity_id" = 247912589751782312;
	    retryNumber = 0;
	    sdk = "ios0.11.17";
	    "session_id" = 256163705274246442;
	    source = ios;
	    stage = test;
	}

```

**Comment by yonihei** [comment] 2016-05-03 22:21
we use cordova 5.0.0 and Branch v2.0.12, iphone 6 (or 6s im not sure) with 9.2
It is a bit large project, but ill try to include the important parts of the code. I deleted some hopefully irrelevant parts of the code.
Once we take off "$android_url" and "$ios_url" from contentMetadata  at linkData , the iphone's links do not send the user to the right deepview. I'd expect our linkOptions to do the job. I hope im not missing something trivial here:
(it is working iphone with the contentMetadata, i just wish to contribute our share to the QA)

`var linkData = {
          contentMetadata : {
            // extra params for mixpanel & outside invitation page
          ......
           .....
  
**            "$android_url" : "http://bla.html",
            "$ios_url"     : "http://bla.html",**
            "myEvent": myEvent
          },
          canonicalIdentifier: 'identifier',
          title: someString,   //'Just another title',
          contentDescription: someString   //'Just another description',
          contentImageUrl: "bla.jpg", //needs to be jpg to work in android,
          contentIndexingMode: 'public'
      };
      var linkOptions = {
         "$android_url" : "http://bla.com.html",

         "$ios_url"     : "http://bla.com.html",
         "$custom_sms_text" : someString
      };`


`       var branchUniversalObj = null;
         Branch.createBranchUniversalObject(linkData)
         .then(function (newBranchUniversalObj) {
            // Success Callback
            branchUniversalObj = newBranchUniversalObj;
            $log.debug("newBranchUniversalObj:");
            $log.debug(newBranchUniversalObj);

            branchUniversalObj.generateShortUrl({

              channel: 'sms',
              feature: 'share'
              }, linkOptions
            ).then(function (res) {

               $log.debug("generateShortUrl's output is: " + res.url);
 

            }, function (error) { //branchUniversalObj err

                  Utils.myThrowError("(#300000)" ,"parse", false);

               return null;
            });
         }, function (err) {  //Branch.createBranchUniversalObject err
                  Utils.myThrowError("(#300001)" ,"parse", false);
               return null;
         });`

**Comment by renesansz** [comment] 2016-05-04 02:28
I'll update the documentation in regards to the description of the parameters.
At the moment you could try using `$fallback_url` which will be the default to all platform if none is specified see this [guide](https://dev.branch.io/getting-started/configuring-links/guide/) for info. Also, currently known issue for deeplinks is that it does not work with emulators so you will be needing an actual device to test this.

**Comment by yonihei** [comment] 2016-05-04 08:25
Thanks (to my embarrassment i didn't notice this doc in branch).
Please close this issue whenever you see fit

**Comment by renesansz** [comment] 2016-05-04 09:09
sure, no worries 👍
I've submitted PR #137 to make it clear for the parameter descriptions.
Closing issue now

**Closed by renesansz** 2016-05-04 09:09 UTC
