### ISSUE TITLE
DeepLinkHandler is global, how can i call my service?

### ISSUE THREAD

**Issue by yonihei** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#128] opened 2016-04-26 08:04 UTC
Hello,
We have a problem about DeepLinkHandler . Since we are forced to make it a global function, we do not know how to use our angular services that we want.

1) Does DeepLinkHandler  really need to be global to be used?
2) if so, how do we call our own angular services/controller functions in order to log in the user etc? A global function does not "know" them since it is not in its scope...

(already emailed brunch about it and didn't get a real answer)
Thanks,
Jonathan

**Comment by jstoup111** [comment] 2016-04-26 16:48
```
(function() {
    'use strict';

    var core = angular.module('myapp.core');

    var config = {
        appErrorPrefix: '[myapp Error] ',
        appTitle:       'myApp'
    };

    core.value('config', config);

    core.run(CoreRun)
        .config(CoreConfig);

    CoreRun.$inject = ['$ionicPlatform'];

    function CoreRun($ionicPlatform) {
        $ionicPlatform.ready(function() {
            if(window.cordova && window.cordova.plugins.Keyboard) {
                cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false); // jshint ignore:line
                cordova.plugins.Keyboard.disableScroll(true); // jshint ignore:line
            }

            if(window.StatusBar) {
                // org.apache.cordova.statusbar required
                StatusBar.styleDefault(); // jshint ignore:line
            }
        });
    }
})();

// Set Location of opening location
function handleOpenURL(url) {
    if(url.indexOf('myapp://') !== -1) {
        cordova.fireDocumentEvent('handleopenurl', {url: url});
    }
}

if('cordova' in window) {
    cordova.addStickyDocumentEventHandler('handleopenurl');
}

function DeepLinkHandler(link) {
    if(link.url) {
      if(link.url === 'myapp://') {
          link.url = 'myapp://link';
      }

        handleOpenURL(link.url);
    }
}

function NonBranchLinkHandler(link) {
    if(link.url) {
      if(link.url === 'myapp://') {
          link.url = 'myapp://';
      }

        handleOpenURL(link.url);
    }
}
```

```
(function() {
  'use strict';

  angular
    .module('myapp.openUrl', ['myapp.myapp-injection'])
    .factory('openUrlService', ['$location', '$rootScope', '$ionicHistory', openUrlService])
    .run(['openUrlService', run]);

  function openUrlService($location, $rootScope, $ionicHistory) {
    return {
      handleOpenUrl: handleOpenUrl,
      onResume:      onResume
    };

    function openUrl(url) {
      $ionicHistory.nextViewOptions({
        historyRoot:      true,
        disableBack:      true,
        disableAnimation: true
      });

         window.location.hash = url.replace('myapp://', '');
        $rootScope.$broadcast('handleopenurl', url);

        window.cordova.removeDocumentEventHandler('handleopenurl');
        window.cordova.addStickyDocumentEventHandler('handleopenurl');
        document.removeEventListener('handleopenurl', handleOpenUrl);
    }

    function handleOpenUrl(e) {
      openUrl(e.url);
    }

    function onResume() {
      document.addEventListener('handleopenurl', handleOpenUrl, false);
    }
  }

  function run(openUrlService) {
    if(openUrlService) {
      document.addEventListener('handleopenurl', openUrlService.handleOpenUrl, false);
      document.addEventListener('resume', openUrlService.onResume, false);
    }
  }

})();
```

**Comment by yonihei** [comment] 2016-04-26 18:40
ohh, so it is basically sending an event signal from javascript to the listener somewhere inside my platform ready.
thanks :)

**Comment by renesansz** [comment] 2016-04-27 01:15
@yonihei ,
Please confirm if this issue has been resolved so that we can close it now.
Thanks 😄

**Comment by renesansz** [comment] 2016-04-27 01:15
Issue resolved, closing now.

**Closed by renesansz** 2016-04-27 01:15 UTC

**Comment by yonihei** [comment] 2016-05-02 18:16
note, the name handleOpenUrl seems to be colliding with facebook4 plugin

**Comment by jstoup111** [comment] 2016-05-02 19:19
You might be using https://github.com/EddyVerbruggen/Custom-URL-scheme plugin. handleOpenUrl function name is irrelevant in this case since Branch handles branch and non-branch links. Just rename the function.

**Comment by haxpor** [comment] 2016-10-28 15:07
I tried this solution on ionic 2 rc1, and it didn't work. The problem is `exception nativeEvalAndFetch : ReferenceError: Can't find variable: DeepLinkHandler` despite initSession() succeeded.

**Comment by haxpor** [comment] 2016-10-29 06:04
I modified @jstoup111 's solution to general one and use 'sidemenu' template from ionic 1. See here https://gist.github.com/haxpor/644893a22f79bc910db37d79d36a2f00.

**Comment by ethanneff** [comment] 2016-11-02 21:24
This is the solution I have been using to integrate Branch's global DeepLinkHandler into Ionic/Angular.


# Global DeepLinkHandler into Angular 

> listen to Branch data, save to an angular `DeepLink` factory

```js
// must be a global function
function DeepLinkHandler(data) {
  if (data) {
    // access the angular Factory('DeepLink')
    angular.element(document.querySelector('[ng-app]')).injector().get('DeepLink').set(data);
    console.log('Data Link handler response: ' + JSON.stringify(data));
  } else {
    console.error('Data Link handler no data');
  }
}
```

> angular `DeepLink` factory

```js
angular.module('starter.services', [])

.factory('DeepLink', function($window, $timeout) {
  var data = {};

  return {
    get: function() {
      return data;
    },
    set: function(json) {
      // use the angular version of timeout
      $timeout(function() {
        // set the data
        data = json;
        // navigate example
        $window.location = "#/tab/chats/3";
      }, 0);
    }
  };
});
```

> access angular `DeepLink` Factory

```js
angular.module('starter.controllers', [])

.controller('DashCtrl', function($scope, DeepLink) {
  $scope.content = {}
  $scope.buttonPressed = function() {
    // put branch data into a label that has ng-model content.data
    $scope.content.data = JSON.stringify(DeepLink.get());
  };
})
```
