### ISSUE TITLE
Cordova integration getting build error for iOS with phonegap

### ISSUE THREAD

**Issue by Mushaqdeen** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#100] opened 2016-04-13 07:00 UTC
Hello,
      We integrated the new version of branch into our cordova app. Its working good in Android, but when we build the app with phonegap the build server returns the error as "Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture." for iOS.

Please help us to resolve this issue.

**Comment by renesansz** [comment] 2016-04-13 22:59
Can you provide more details in regards to this issue?
* Complete error log
* Cordova & plugin versions
* iOS version

Thanks

**Comment by Mushaqdeen** [comment] 2016-04-15 07:06
**Phonegap build complete error log**
[error-log.txt](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/files/220486/error-log.txt)

**My complete config.xml file**
[config.txt](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/files/220489/config.txt)

**Comment by renesansz** [comment] 2016-04-18 00:42
Thanks @Mushaqdeen ,
Will look in to the logs provided. I'll give you a feedback once I've found the cause of the error.

Cheers,
Rene

**Comment by renesansz** [comment] 2016-04-18 01:46
@Mushaqdeen , could you also include the list of plugins that you are using?
Do `cordova plugin list` in the command line.

Thanks

**Comment by Mushaqdeen** [comment] 2016-04-18 06:41
@renesansz , In the config file there will be the list of plugins that I used in my project.

**Comment by renesansz** [comment] 2016-04-19 01:15
I see, will look into it.

**Comment by renesansz** [comment] 2016-04-19 08:10
Hi @Mushaqdeen , For the nth time in creating test app, I can't replicate the issue that you are having.
However I've found this article related with 64-bit support for iOS ([link](http://phonegap.com/blog/2015/01/20/ios-64bit-support/)).
So I've tried to increase the minimum Cordova build version from `3.0.0` to `3.5.0` hoping that this would resolve the issue.
See & test PR #114 if this will resolve the issue.

Cheers,
Rene

**Comment by lededje** [comment] 2016-04-20 08:59
Had this issue, I think I solved it indirectly by specifying the deployment target to be 7 (something required for intercom.io integration).

**Comment by Mushaqdeen** [comment] 2016-04-23 05:28
Hello,     Now the build got success without any error, but the Branch.initSession() not working also not works the DeepLinkHandler(data) function in iOS.
function DeepLinkHandler(data) {    alert(JSON.stringify(data));}

**Comment by renesansz** [comment] 2016-04-25 01:00
@Mushaqdeen ,
Good to know that it fixes your build error. Closing the issue now.
For the mean time, could you report a separate issue for this?

```
Hello,     Now the build got success without any error, but the Branch.initSession() not working also not works the DeepLinkHandler(data) function in iOS.
function DeepLinkHandler(data) {    alert(JSON.stringify(data));}
```

Cheers,
Rene

**Closed by renesansz** 2016-04-25 01:00 UTC
