### ISSUE TITLE
iOS plugin not necessarily returning the latest params

### ISSUE THREAD

**Issue by pragunvohra** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#88] opened 2016-03-25 17:08 UTC
Alternating between opening our app from the home screen and opening it via a link that I generated (https://bnc.lt/BpSc/6rY8bdZZXr) (note the latest code is not on production so grabbing the production app from the App store won't help here), the following code in JS doesn't necessarily return the latest params. Sometimes when I open the app from my home screen, the latest referring params say that they are from the link and vice versa:

```javascript
window.Branch.initSession().then(function(params) { 
    console.log("The latest params should be: ", params);
}
```

```javascript
window.Branch.initSession().then(function() { 
  window.Branch.getLatestReferringParams().then(function(params) {
    console.log("The latest params should be: ", params);
  }
}
```

We call initSession in these places:
```javascript
deviceReady().then(...);
document.addEventListener("resume", ...);
onRegister // function that is hit when a new user registers
```

Many times I receive these params in DeepLinkHandler (which are wrong):
```javascript
{+is_first_session: false, +clicked_branch_link: false}
```

and sometimes I receive the proper params for my link, but when I navigate open the app from my iPhone's home screen instead of via a link.

I haven't looked into if the issue happens for getFirstReferringParams().

This is potentially the last issue that is blocking us from deploying to production, so a resolution here would be great.

Thanks.

**Comment by aaustin** [comment] 2016-03-27 01:07
Hey @pragunvohra - I think the problem is that you're trying to call getLatestReferring in the callback to initSession. We fetch the params asynchronously and will pass them back to the `DeepLinkHandler` method when they're available: see initSession:
https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#initsession

If you call getLatest before the params are fetched from the server, it will return an empty set.

**Comment by pragunvohra** [comment] 2016-03-27 01:13
Thanks for the response, @aaustin. I thought the same thing as well, though I was also manually calling into getLatestReferringParams() from the console and seeing the same behavior (well past my initParams call), though I'll verify again on my end.

**Comment by aaustin** [comment] 2016-04-23 22:59
We've confirmed that this is the intended functionality of the library and will be closing this out. Apologies.

**Closed by aaustin** 2016-04-23 22:59 UTC
