### ISSUE TITLE
shareSheet Facebook option appears to be broken

### ISSUE THREAD

**Issue by GrahenKraken** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#106] opened 2016-04-15 10:18 UTC
I am using Cordova 6.1.1. on a Samsung Galaxy Grand Prime (SM-G531H) with Android 5.1.1. The plugin is the latest version (downloaded about an hour ago). I will test on a Nexus 5 soon to confirm if necessary.

![ss](https://cloud.githubusercontent.com/assets/10092830/14558675/04ba52f0-0304-11e6-8c1d-2c717c3cdf37.png)

The facebook icon is broken, and choosing the option opens up a blank screen for a few seconds, then closes it with no callback called in JS.

Update: the issue is there only if there is no native Facebook app installed on the device.

**Comment by GrahenKraken** [comment] 2016-04-15 12:56
Update: I just tested the exact same build on a Nexus 5 device, and the button looks and works just fine.

**Comment by renesansz** [comment] 2016-04-18 00:41
Hello @GrahenKraken ,
I cannot replicate the issue, not sure if this is the plugin's fault or not?
This is what I've got
![](https://lh6.googleusercontent.com/hO56wI6AZAxzbaJYllRzcj4IoUjRs0go1eF4rkD-Y5ewP8lLvouagA5oFFtuHj3Pm2d4=w2560-h1984)

Could you try it on different phones?

**Comment by GrahenKraken** [comment] 2016-04-18 00:57
@renesansz do you have the Facebook application installed? I have the problem only when I don't have Facebook installed.

**Comment by renesansz** [comment] 2016-04-18 01:13
This is how it looks like when there's no Facebook application installed.
![](http://i.imgur.com/uSrx7y4.png)

**Comment by GrahenKraken** [comment] 2016-04-18 01:20
Could it be because I have the facebook plugin installed? (jeduan/facebook4
<https://github.com/jeduan/cordova-plugin-facebook4>) I will do some more
testing and report back, I'll try rebooting and checking if anything else
makes the share-sheet "forget" about Facebook.

**Comment by renesansz** [comment] 2016-04-18 01:43
cool, thanks!
Please do try that solution, that might solve your problem. Because from my point of view, I think this issue is not caused by the plugin anymore.

**Comment by renesansz** [comment] 2016-04-18 04:27
@GrahenKraken Let me know if this issue has been resolved.

Thanks

**Comment by aaustin** [comment] 2016-04-23 22:58
Closing out unless otherwise noted.

**Closed by aaustin** 2016-04-23 22:58 UTC
