### ISSUE TITLE
showShareSheet causes app crash

### ISSUE THREAD

**Issue by GrahenKraken** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#102] opened 2016-04-13 17:32 UTC
I'm calling showShareSheet like so:
```
Branch.createBranchUniversalObject({
  ...
}).then(function (branchUniversalObj) {
branchUniversalObj.showShareSheet({
 ...
},{});
}, function (err) {
// Error Callback
console.error(err);
});
```
Everything seems in order, but every couple of times, selecting an app from the "Show More" menu (e.g. Hangouts) crashes the app.
My logcat experience is limited, but this is what I managed to pull out from CordovaBranchSDK and AndroidRuntime:
```
D/CordovaBranchSDK( 4357): start showShareSheet()
D/CordovaBranchSDK( 4357): start createLinkProperties()
D/CordovaBranchSDK( 4357): inside onShareLinkDialogLaunched
D/CordovaBranchSDK( 4357): inside onChannelSelected
D/CordovaBranchSDK( 4357): channelName: Hangouts
D/CordovaBranchSDK( 4357): inside onLinkCreate
D/AndroidRuntime( 4357): Shutting down VM
E/AndroidRuntime( 4357): FATAL EXCEPTION: main
E/AndroidRuntime( 4357): Process: com.selfikon.anna, PID: 4357
E/AndroidRuntime( 4357): java.lang.RuntimeException: Unable to pause activity {com.selfikon.anna/com.selfikon.anna.MainActivity}: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime( 4357): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3260)
E/AndroidRuntime( 4357): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3219)
E/AndroidRuntime( 4357): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3194)
E/AndroidRuntime( 4357): 	at android.app.ActivityThread.access$1000(ActivityThread.java:151)
E/AndroidRuntime( 4357): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1314)
E/AndroidRuntime( 4357): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4357): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4357): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 4357): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4357): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4357): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 4357): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 4357): Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
E/AndroidRuntime( 4357): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6357)
E/AndroidRuntime( 4357): 	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:909)
E/AndroidRuntime( 4357): 	at android.view.ViewGroup.invalidateChild(ViewGroup.java:4690)
E/AndroidRuntime( 4357): 	at android.view.View.invalidateInternal(View.java:11801)
E/AndroidRuntime( 4357): 	at android.view.View.invalidate(View.java:11765)
E/AndroidRuntime( 4357): 	at android.view.View.startAnimation(View.java:17859)
E/AndroidRuntime( 4357): 	at io.branch.referral.AnimatedDialog.slideClose(AnimatedDialog.java:118)
E/AndroidRuntime( 4357): 	at io.branch.referral.AnimatedDialog.cancel(AnimatedDialog.java:53)
E/AndroidRuntime( 4357): 	at io.branch.referral.ShareLinkManager.cancelShareLinkDialog(ShareLinkManager.java:92)
E/AndroidRuntime( 4357): 	at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityPaused(Branch.java:3053)
E/AndroidRuntime( 4357): 	at android.app.Application.dispatchActivityPaused(Application.java:217)
E/AndroidRuntime( 4357): 	at android.app.Activity.onPause(Activity.java:1468)
E/AndroidRuntime( 4357): 	at org.apache.cordova.CordovaActivity.onPause(CordovaActivity.java:228)
E/AndroidRuntime( 4357): 	at android.app.Activity.performPause(Activity.java:6101)
E/AndroidRuntime( 4357): 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
E/AndroidRuntime( 4357): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3246)
E/AndroidRuntime( 4357): 	... 11 more
D/CordovaBranchSDK( 4357): inside onShareLinkDialogDismissed
```
I'm not that great with native development, so any help would be great. From what I see here, my best guess is that a background thread is trying to work with the UI, but that is as far as I've gotten.

**Comment by renesansz** [comment] 2016-04-13 23:55
@GrahenKraken ,
Let me try to replicate the issue. At the moment, can you provide additional details for your setup?
eg: Cordova, Android, and plugin versions.

Thanks

**Comment by GrahenKraken** [comment] 2016-04-13 23:59
I produced the issue on the testbed app on a Nexus 5 device. Standard
setup, just built it and used the "show share sheet" button, and got "The
app has stoppes working". I can provide more detailed information tomorrow,
since I won't be awake much longer :)

**Comment by renesansz** [comment] 2016-04-14 02:48
okay thanks, that would do.
At the moment I'll try to reproduce the bug and give you feedback on my findings and its fix.

**Comment by renesansz** [comment] 2016-04-14 06:50
Hi @GrahenKraken ,
I don't have a Nexus 5 device, so I used Samsung S4 instead.
However I've been trying to resolve the issue but somehow I can't find a way to replicate the error.
Does this only happen on a specific device?
I've tried also testing with ASUS Zenfone and still it doesn't have any error.

**Comment by GrahenKraken** [comment] 2016-04-14 11:26
Hi @renesansz , thanks for the speedy responses.
I am currently running your testbed app.
My Cordova version is 6.1.1, I am running it on a Samsung Galaxy Grand Prime (SM-G531H) with Android 5.1.1. The plugin is the latest version from this repo, which seems to be 2.0.9 (downloaded again yesterday to make sure it's fresh)

I start up the testbed app, get the initial alerts, click "Init Branch Universal Object", get those alerts.
Then I click "Share Sheet", select "Show More", then select Hangouts as an option, the list slides down, and the crash happens just before I get to choose my Hangouts account, with the "Choose Account" dialog behind the error "alert". It happens every couple of times. If it doesn't, I just go back (without selecting a Hangouts account) and retry until it crashes.

**Comment by renesansz** [comment] 2016-04-14 18:14
@GrahenKraken ,
I see, so far I don't know the reason why it happens sometimes.
Let me investigate further on what's causing this error.

**Comment by renesansz** [comment] 2016-04-15 03:16
Hi @GrahenKraken ,
On the nth time, I wasn't able to reproduce the error.
So what I did was to re-inspect the error log that you've produced and it stated
```
E/AndroidRuntime( 4357): java.lang.RuntimeException: Unable to pause activity {com.selfikon.anna/com.selfikon.anna.MainActivity}: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
```

It was mentioned before in regards to threading on this [discussion](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/pull/76#issuecomment-199493327).
So in the PR #105 I implemented it on the plugin, I hope this would resolve the issue that you are having.

Cheers,
Rene

**Comment by GrahenKraken** [comment] 2016-04-15 08:53
Hey @renesansz ,

#105 resolved the issue, and from looking at the changes, it is exactly what was needed :)

However, now the "Facebook" option on the shareSheet seems broken:
![ss](https://cloud.githubusercontent.com/assets/10092830/14556358/2ab71512-02f8-11e6-8313-5ef02edcabdc.png)

Selecting the option opens up a blank screen for a few seconds and closes with no callback in JS.
P.S. Not sure if I should open up a new issue for this?

**Comment by renesansz** [comment] 2016-04-15 09:30
@GrahenKraken ,
Glad to hear that fix works for you.
Yes, please open up another issue for this and provide the logs & how the error occurs.

Closing PR.

Cheers,
Rene

**Closed by renesansz** 2016-04-15 09:30 UTC
