### ISSUE TITLE
Can't get the plugin to build in Phonegap Build - Missing iOS header file

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#51] opened 2016-03-02 16:06 UTC
I'm trying to do a build through phonegap build service, but it's failing for both iOS and Android.  

For comparison purposes, version 1.8 succeeded in PGB, it was just broken when you tried to use it.  I know this isn't support for PGB, but I feel like something introduced here isn't playing nicely.  

Here is an error from the iOS build, it's not totally helpful but it's something:

** BUILD FAILED **

The following build commands failed:
	CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.o VeociDEV/Plugins/io.branch.sdk/BranchSDK.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

It doesn't give any detail on WHY it failed.  If this is not something you can really help out with, you can just close this and I'll try to push the PGB guys, but talking to them is like working in a vacuum.  That's why I was hoping we could resolve it here.

**Comment by gabaum10** [comment] 2016-03-02 16:08
What version of cordova is this expecting?  Maybe PGB isn't using the right version?

**Comment by gabaum10** [comment] 2016-03-02 16:18
So I upgraded to cli-6.0.0 on PGB and now the android version builds correctly.  Unfortunately, iOS is still failing with the error above.

**Comment by gabaum10** [comment] 2016-03-02 16:52
Oh a little more info here.  It looks like you're missing the iOS header file, that's why it's failing:

CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.o VeociDEV/Plugins/io.branch.sdk/BranchSDK.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /tmp/gimlet/1050751/project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-generated-files.hmap -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-own-target-headers.hmap -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-all-target-headers.hmap -iquote /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-project-headers.hmap -I/tmp/gimlet/1050751/project/build/include -I/tmp/gimlet/1050751/project/build/usr/local/lib/include -I/tmp/gimlet/1050751/project/build/UninstalledProducts/include -I/tmp/gimlet/1050751/project/build/UninstalledProducts/iphoneos/include -I/tmp/gimlet/1050751/project/build -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources/armv7 -I/tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources -F/tmp/gimlet/1050751/project/build -FVeociDEV/Plugins/io.branch.sdk -include /var/folders/8r/065_jhkn1qqf03lr71kjj6480000gp/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/VeociDEV-Prefix-fcqnucwoukkzdpefevwvxpswqvma/VeociDEV-Prefix.pch -MMD -MT dependencies -MF /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.d --serialize-diagnostics /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.dia -c /tmp/gimlet/1050751/project/VeociDEV/Plugins/io.branch.sdk/BranchSDK.m -o /tmp/gimlet/1050751/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.o
In file included from /tmp/gimlet/1050751/project/VeociDEV/Plugins/io.branch.sdk/BranchSDK.m:8:
VeociDEV/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: 'Branch/Branch.h' file not found
#import <Branch/Branch.h>
        ^
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.o VeociDEV/Plugins/io.branch.sdk/BranchSDK.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by aaustin** [comment] 2016-03-02 17:00
@gabaum10 I've alerted the eng team and hope to have this addressed by tomorrow.

**Comment by aaustin** [comment] 2016-03-02 17:00
Thanks for all the info!

**Comment by ZackMattor** [comment] 2016-03-02 19:20
@gabaum10 are you using master? I'm pretty sure this was fixed yesterday.. they need to do a new release.

**Comment by gabaum10** [comment] 2016-03-02 19:30
I'm building out of npm.  So it likely needs to be pushed there if it hasn't yet.

**Comment by ZackMattor** [comment] 2016-03-02 19:35
@gabaum10 to test master you can try this.

```
    <plugin name="branch-cordova-sdk" version="https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK.git">
        <variable name="BRANCH_LIVE_KEY" value="key_here" />
        <variable name="URI_SCHEME" value="your_uri_scheme" />
    </plugin>
```

**Comment by gabaum10** [comment] 2016-03-02 19:47
Did not realize you could do that.  Learn something new every day.  I did that and the iOS version built.  However, now the android version is failing with the following error: 

:compileReleaseJavaWithJavac/project/src/io/branch/BranchSDK.java:776: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK);
                ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:776: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK);
                                          ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:776: error: package PluginResult does not exist
                PluginResult result = new PluginResult(PluginResult.Status.OK);
                                                                   ^
/project/src/io/branch/BranchSDK.java:790: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK);
                ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:790: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK);
                                          ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:790: error: package PluginResult does not exist
                PluginResult result = new PluginResult(PluginResult.Status.OK);
                                                                   ^
/project/src/io/branch/BranchSDK.java:834: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK, response);
                ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:834: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK, response);
                                          ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:834: error: package PluginResult does not exist
                PluginResult result = new PluginResult(PluginResult.Status.OK, response);
                                                                   ^
/project/src/io/branch/BranchSDK.java:861: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK, response);
                ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:861: error: cannot find symbol
                PluginResult result = new PluginResult(PluginResult.Status.OK, response);
                                          ^
  symbol:   class PluginResult
  location: class BranchSDK.ShowShareSheetListener
/project/src/io/branch/BranchSDK.java:861: error: package PluginResult does not exist
                PluginResult result = new PluginResult(PluginResult.Status.OK, response);
                                                                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
12 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED



In the little explanation spot, it says 

"Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: BranchSDK.java - You can fix this here"

**Comment by ZackMattor** [comment] 2016-03-02 20:00
Yup.... for that you can look here.... https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/50

**Comment by gabaum10** [comment] 2016-03-02 20:06
Yeah, it's working in NPM.  The target API version is 21 and the minimum version is 19.

**Comment by ZackMattor** [comment] 2016-03-02 20:41
@gabaum10 Yeah... its still failing to build for me on android with the NPM package :(

**Comment by gabaum10** [comment] 2016-03-02 21:05
Strange.  It's working for me.  I'm currently building off of it right now so I can keep working on the project I need branch for.  

Did you try setting the target API versions like this?

`<preference name="android-minSdkVersion" value="19" />
<preference name="android-targetSdkVersion" value="21" />
`

**Comment by ZackMattor** [comment] 2016-03-02 21:18
Yup.. I have those exact versions set under android..

```
    <platform name="android">
        <preference name="android-minSdkVersion" value="19" />
        <preference name="android-targetSdkVersion" value="21"/>
        ....
    </platform>
```

**Comment by ZackMattor** [comment] 2016-03-02 21:19
do you have the newest version of the npm package?... even thought it looks like they've only done 1 on the 2.x releases

**Comment by gabaum10** [comment] 2016-03-02 21:20
I should, I'm not specifying the version, which I believe results in building with the latest version.  

So I'm actually not passing the preferences in the platform tag.  It's just at the top level of the XML doc.

**Comment by ZackMattor** [comment] 2016-03-02 21:25
I have `<plugin name="branch-cordova-sdk" version="2.0.0">` specified in my config.xml... meh. this is frustrating. haha

I moved my version declarations outside of the android block and it doesn't help.

**Comment by gabaum10** [comment] 2016-03-02 21:26
Do you have to add the source="npm" to the plugin tag?  Or does it default to npm?

**Comment by ZackMattor** [comment] 2016-03-02 21:28
Pretty sure it defaults to npm.. I can see that it's getting it fron NPM via the logs.

**Comment by AdrianMF** [comment] 2016-03-03 10:10
Getting similar issues as to what is describe here, when I install via NPM, I get the ios missing header file error and when trying through the git repo or source I get the [PluginResult](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/50) android error.

**Comment by renesansz** [comment] 2016-03-04 04:11
@AdrianMF 
Yes, there's a missing import for Android.
I'm going to submit the fix later on.

For other developers getting the error, could you try to run the plugin locally first? then please provide the errors given.

Also, please give me the details for the `cordova, npm, Android versions` also, please provide the `config.xml` for your setup.

Thanks

**Comment by jestoniyap** [comment] 2016-03-04 06:29
#56 Referenced pull request for missing import in Android.

**Comment by gabaum10** [comment] 2016-03-04 11:45
I've confirmed this is fixed in master for me.

**Comment by aaustin** [comment] 2016-03-04 18:58
Pulled in and pushed to NPM.

**Comment by gabaum10** [comment] 2016-03-04 19:58
So I just tested the NPM build.  It's not working for me from there.  I'm not sure what didn't get pulled in, but I'm still getting this error.  When I build from master it works correctly:

CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.o VeociDEV/Plugins/io.branch.sdk/BranchSDK.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/m1/wl3zc68x40z6cn12m764qkf80000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-generated-files.hmap -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-own-target-headers.hmap -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-all-target-headers.hmap -iquote /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build/UninstalledProducts/iphoneos/include -I/project/build -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources/armv7 -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources -F/project/build -FVeociDEV/Plugins/io.branch.sdk -include /var/folders/m1/wl3zc68x40z6cn12m764qkf80000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/VeociDEV-Prefix-awussjfufpkqgudjucpcuwdkwbxo/VeociDEV-Prefix.pch -MMD -MT dependencies -MF /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.d --serialize-diagnostics /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.dia -c /project/VeociDEV/Plugins/io.branch.sdk/BranchSDK.m -o /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/BranchSDK.o
In file included from /project/VeociDEV/Plugins/io.branch.sdk/BranchSDK.m:8:
VeociDEV/Plugins/io.branch.sdk/BranchSDK.h:8:9: fatal error: **'Branch/Branch.h' file not found
#import <Branch/Branch.h>**

**Comment by gabaum10** [comment] 2016-03-04 20:10
I just confirmed building out of master again.  It works correctly.  Looks like something got missed?

**Comment by ZackMattor** [comment] 2016-03-04 20:29
^ Same here. the ios build has regression it looks like... this was merged into master at one point. Did the merge go wrong?

**Comment by AdrianMF** [comment] 2016-03-04 20:31
@gabaum10 I have the same issue with NPM, was able to build with master. What I noticed is that there are some missing simlinks in the NPM version

Here is the directory structure from the master build (works):
<img width="315" alt="screen shot 2016-03-04 at 5 29 15 pm" src="https://cloud.githubusercontent.com/assets/1189227/13539371/c449df4c-e22e-11e5-8df8-1d47e2a986c9.png">

Here it is from NPM (fails):
<img width="266" alt="screen shot 2016-03-04 at 5 23 34 pm" src="https://cloud.githubusercontent.com/assets/1189227/13539384/d9256c6a-e22e-11e5-82af-0695a87f1e50.png">

**Comment by aaustin** [comment] 2016-03-04 20:58
*face palm* will try to fix this tonight

**Comment by aaustin** [comment] 2016-03-06 07:11
It seems that NPM doesn't allow symlinks https://issues.apache.org/jira/browse/CB-6092 We'll need to replace the Branch framework with the source code and re-deploy. I'll have the engineers take a look.

**Comment by jestoniyap** [comment] 2016-03-07 12:19
@aaustin I have replaced the framework with the actual source files from the iOS SDK repo. Kindly check and see if it works on PhoneGap. Thanks.

**Comment by aaustin** [comment] 2016-03-07 16:03
Hey team - I just deployed to NPM. It should fix that simlink issue!

**Comment by gabaum10** [comment] 2016-03-07 16:07
Works for me!  Thanks for all the work getting this set up.

**Comment by aaustin** [comment] 2016-03-07 18:30
Nice ! Closing this out then.

**Closed by aaustin** 2016-03-07 18:30 UTC
